
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author osqui
 */
public class loteria extends javax.swing.JFrame {

    /**
     * Creates new form FradelRandom
     */
    public loteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonUno = new javax.swing.ButtonGroup();
        botonDos = new javax.swing.ButtonGroup();
        botonTres = new javax.swing.ButtonGroup();
        anim = new javax.swing.ButtonGroup();
        botonDoss = new javax.swing.ButtonGroup();
        botonTress = new javax.swing.ButtonGroup();
        botonCuatroo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ejecutar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        seleccionarUno = new javax.swing.JRadioButton();
        seleccionarDos = new javax.swing.JRadioButton();
        seleccionarTres = new javax.swing.JRadioButton();
        resultado = new javax.swing.JTextField();
        ACEPTAR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        tricesatox = new javax.swing.JRadioButton();
        tirex = new javax.swing.JRadioButton();
        velociraptor = new javax.swing.JRadioButton();
        ankylosaurus = new javax.swing.JRadioButton();
        titulo = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ejecutar.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("Loteria");

        seleccionarUno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seleccionarUno.setText("o   - 100");

        seleccionarDos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seleccionarDos.setText("100 - 200");

        seleccionarTres.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        seleccionarTres.setText("200 - 500");
        seleccionarTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarTresActionPerformed(evt);
            }
        });

        resultado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        ACEPTAR.setText("EJECUTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ejecutarLayout = new javax.swing.GroupLayout(ejecutar);
        ejecutar.setLayout(ejecutarLayout);
        ejecutarLayout.setHorizontalGroup(
            ejecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecutarLayout.createSequentialGroup()
                .addGroup(ejecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ejecutarLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ACEPTAR))
                    .addGroup(ejecutarLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(ejecutarLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(ejecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ejecutarLayout.createSequentialGroup()
                                .addGroup(ejecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seleccionarDos)
                                    .addComponent(seleccionarUno, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seleccionarTres))
                                .addGap(71, 71, 71)))))
                .addContainerGap(1430, Short.MAX_VALUE))
        );
        ejecutarLayout.setVerticalGroup(
            ejecutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ejecutarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(seleccionarUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionarDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionarTres)
                .addGap(18, 18, 18)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ACEPTAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", ejecutar);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        anim.add(tricesatox);
        tricesatox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tricesatox.setText("Tricesatox");
        tricesatox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tricesatoxActionPerformed(evt);
            }
        });

        anim.add(tirex);
        tirex.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tirex.setText("Tirex");
        tirex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirexActionPerformed(evt);
            }
        });

        velociraptor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        velociraptor.setText("Velociraptor");
        velociraptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velociraptorActionPerformed(evt);
            }
        });

        ankylosaurus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ankylosaurus.setText("Ankylosaurus");
        ankylosaurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ankylosaurusActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titulo.setText("Selecione un aminal");

        salir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        salir.setText("Salir");
        salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(titulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tricesatox)
                                    .addComponent(tirex)
                                    .addComponent(velociraptor)
                                    .addComponent(ankylosaurus)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titulo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tricesatox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tirex)
                        .addGap(18, 18, 18)
                        .addComponent(velociraptor)
                        .addGap(18, 18, 18)
                        .addComponent(ankylosaurus)
                        .addGap(18, 18, 18)
                        .addComponent(salir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed


    }//GEN-LAST:event_resultadoActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        if (seleccionarUno.isSelected()) {
            int dato = (int) (Math.random() * 100 + 1);
            String num = Integer.toString(dato);
            this.resultado.setText(num);
        }
        if (seleccionarDos.isSelected()) {
            int dato = (int) (Math.random() * (200 - 100 + 1) + 100);
            String num = Integer.toString(dato);
            this.resultado.setText(num);
        }
        if (seleccionarTres.isSelected()) {
            int dato = (int) (Math.random() * (500 - 100 + 1) + 200);
            String num = Integer.toString(dato);
            this.resultado.setText(num);
        }
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

    }//GEN-LAST:event_salirActionPerformed

    private void seleccionarTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarTresActionPerformed

    private void tricesatoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tricesatoxActionPerformed
        if (tricesatox.isSelected()){
            ImageIcon tricesatox = new ImageIcon(getClass().getResource("/imagen/e.jpg"));
            imagen.setIcon( tricesatox);

        }
    }//GEN-LAST:event_tricesatoxActionPerformed

    private void tirexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirexActionPerformed
        if (tricesatox.isSelected()){
            ImageIcon tricesatox = new ImageIcon(getClass().getResource("/imagen/i.jpg"));
            imagen.setIcon( tricesatox);

        }
    }//GEN-LAST:event_tirexActionPerformed

    private void velociraptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velociraptorActionPerformed
        if (velociraptor.isSelected()){
            ImageIcon tricesatox = new ImageIcon(getClass().getResource("/imagen/o.jpg"));
            imagen.setIcon( tricesatox);

        }
    }//GEN-LAST:event_velociraptorActionPerformed

    private void ankylosaurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ankylosaurusActionPerformed
        if (ankylosaurus.isSelected()){
            ImageIcon ankylosaurus = new ImageIcon(getClass().getResource("/imagen/a.jpg"));
            imagen.setIcon(ankylosaurus);

        }
    }//GEN-LAST:event_ankylosaurusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.ButtonGroup anim;
    private javax.swing.JRadioButton ankylosaurus;
    private javax.swing.ButtonGroup botonCuatroo;
    private javax.swing.ButtonGroup botonDos;
    private javax.swing.ButtonGroup botonDoss;
    private javax.swing.ButtonGroup botonTres;
    private javax.swing.ButtonGroup botonTress;
    private javax.swing.ButtonGroup botonUno;
    private javax.swing.JPanel ejecutar;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton salir;
    private javax.swing.JRadioButton seleccionarDos;
    private javax.swing.JRadioButton seleccionarTres;
    private javax.swing.JRadioButton seleccionarUno;
    private javax.swing.JRadioButton tirex;
    private javax.swing.JLabel titulo;
    private javax.swing.JRadioButton tricesatox;
    private javax.swing.JRadioButton velociraptor;
    // End of variables declaration//GEN-END:variables
}
