package edu.jdc.formularios;

import com.formdev.flatlaf.FlatDarkLaf;
import edu.jdc.clases.MiArreglo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jairo
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private MiArreglo miArreglito;
    private final DefaultListModel<String> miModelito = new DefaultListModel<>();

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                mefui();
            }
        });
        listaUno.setModel(miModelito);

    }

    private void mefui() {
        String nombre[] = {"yea", "no"};
        int result = JOptionPane.showOptionDialog(this,
                "¿Desea cerrar el JFrame?", "Confirmar cierre",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, nombre, nombre[0]);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUno = new javax.swing.JPanel();
        textoUno = new javax.swing.JLabel();
        panelDos = new javax.swing.JPanel();
        botonCrear = new javax.swing.JButton();
        botonImprimir = new javax.swing.JButton();
        botonCrearAleatoria = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        botnAgergar = new javax.swing.JButton();
        botnBorrar = new javax.swing.JButton();
        botnVaciar = new javax.swing.JButton();
        panelTres = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUno = new javax.swing.JList<>();
        panelCuatro = new javax.swing.JPanel();
        textoDos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUno.setBackground(new java.awt.Color(255, 255, 0));

        textoUno.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        textoUno.setText("DIAGNOSTICO");

        javax.swing.GroupLayout panelUnoLayout = new javax.swing.GroupLayout(panelUno);
        panelUno.setLayout(panelUnoLayout);
        panelUnoLayout.setHorizontalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        panelUnoLayout.setVerticalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoUno, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        panelDos.setBackground(new java.awt.Color(255, 0, 0));

        botonCrear.setText("Crear Arreglo");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        botonImprimir.setText("imprimir ");
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });

        botonCrearAleatoria.setText("crear aleatorio");
        botonCrearAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearAleatoriaActionPerformed(evt);
            }
        });

        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        botnAgergar.setText("agreagr ultimo");
        botnAgergar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnAgergarActionPerformed(evt);
            }
        });

        botnBorrar.setText("borrar ultimo");
        botnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnBorrarActionPerformed(evt);
            }
        });

        botnVaciar.setText("vaciar arreglo");
        botnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnVaciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDosLayout = new javax.swing.GroupLayout(panelDos);
        panelDos.setLayout(panelDosLayout);
        panelDosLayout.setHorizontalGroup(
            panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botnVaciar)
                    .addComponent(botnBorrar)
                    .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botnAgergar)
                        .addComponent(botonCrearAleatoria)))
                .addGap(18, 18, 18))
        );
        panelDosLayout.setVerticalGroup(
            panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonImprimir)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addGap(18, 18, 18)
                .addComponent(botonCrearAleatoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botnAgergar)
                .addGap(18, 18, 18)
                .addComponent(botnBorrar)
                .addGap(18, 18, 18)
                .addComponent(botnVaciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTres.setBackground(new java.awt.Color(0, 0, 255));

        jScrollPane1.setViewportView(listaUno);

        javax.swing.GroupLayout panelTresLayout = new javax.swing.GroupLayout(panelTres);
        panelTres.setLayout(panelTresLayout);
        panelTresLayout.setHorizontalGroup(
            panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTresLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelTresLayout.setVerticalGroup(
            panelTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTresLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCuatro.setBackground(new java.awt.Color(102, 255, 0));

        textoDos.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        textoDos.setText("SALIR");
        textoDos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelCuatroLayout = new javax.swing.GroupLayout(panelCuatro);
        panelCuatro.setLayout(panelCuatroLayout);
        panelCuatroLayout.setHorizontalGroup(
            panelCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuatroLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(textoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCuatroLayout.setVerticalGroup(
            panelCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelCuatro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panelUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        mefui();
    }//GEN-LAST:event_salirActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        String dataCantidad = JOptionPane.showInputDialog(null, "dame el tamaño del arreglo", "pilas mano", JOptionPane.INFORMATION_MESSAGE);
        if (dataCantidad != null) {
            try {
                int i, cantidad;
                cantidad = Integer.parseInt(dataCantidad);
                miArreglito = new MiArreglo(cantidad);
                miModelito.clear();
                for (i = 0; i < cantidad; i++) {
                    String dataValor = JOptionPane.showInputDialog(null, "ingrese un numero", "pilas mano", JOptionPane.INFORMATION_MESSAGE);
                    if (dataValor == null) {
                        miModelito.addElement("le diste cancelar ");
                        i = cantidad;
                    } else {
                        try {
                            int elValor = Integer.parseInt(dataValor);
                            miArreglito.agregarElemento(i, elValor);
                        } catch (Exception miError) {
                            i--;
                            JOptionPane.showMessageDialog(null, "dijite unicamente caracteres numericos ", "ADVERTENCIa", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                }
            } catch (Exception error) {
                JOptionPane.showMessageDialog(null, "solo dijite caracteres numericos ", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirActionPerformed
        miModelito.clear();
        if (miArreglito == null) {
            miModelito.addElement("no exite ninguna monda ");
        } else {
            miArreglito.imprimit(miModelito);
        }
    }//GEN-LAST:event_botonImprimirActionPerformed

    private void botonCrearAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearAleatoriaActionPerformed
        miModelito.clear();
        miArreglito = new MiArreglo();
        miArreglito.crearAleatorio(5, 9, 100, 200);
        miModelito.addElement("listo man,creado el aleatorio");
        
    }//GEN-LAST:event_botonCrearAleatoriaActionPerformed

    private void botnAgergarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnAgergarActionPerformed
        String datoValor = JOptionPane.showInputDialog(null,"dame un numero","agregar numero",JOptionPane.QUESTION_MESSAGE);
        try {
            if (miArreglito==null) {
                miModelito.addElement("no existe");
                miArreglito = new MiArreglo();
            } else {
                int valorsito =  Integer.parseInt(datoValor);
                miArreglito.agregarElemento(valorsito);
                miModelito.clear();
                miModelito.addElement("agregado");
            }
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null,"pailas","noooo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botnAgergarActionPerformed

    private void botnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnBorrarActionPerformed
        if (miArreglito==null) {
            miModelito.addElement("mano no existe el arreglo");
        } else {
            miModelito.clear();
            miArreglito.eliminarElemento(miModelito);
        }
    }//GEN-LAST:event_botnBorrarActionPerformed

    private void botnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnVaciarActionPerformed
        if (miArreglito==null) {
            miModelito.addElement("no hay  que  vaciar");
        } else {
            miModelito.clear();
            miArreglito.vaciarArreglo();
            miModelito.addElement("se borro arrglo");
        }
    }//GEN-LAST:event_botnVaciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botnAgergar;
    private javax.swing.JButton botnBorrar;
    private javax.swing.JButton botnVaciar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonCrearAleatoria;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaUno;
    private javax.swing.JPanel panelCuatro;
    private javax.swing.JPanel panelDos;
    private javax.swing.JPanel panelTres;
    private javax.swing.JPanel panelUno;
    private javax.swing.JButton salir;
    private javax.swing.JLabel textoDos;
    private javax.swing.JLabel textoUno;
    // End of variables declaration//GEN-END:variables
}
